# fly.toml app configuration file generated for resonance-demos on 2025-01-29T20:29:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resonance-demos'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
